### ISSUE TITLE
clientbuffer doesn't build on znc 1.8.0

### ISSUE THREAD

**Issue by gderaco** [CyberShadow/znc-clientbuffer#11]
I am getting this error
```
znc_1  | make[2]: *** No rule to make target '/znc-data/modules/clientbuffer.cpp', needed by 'CMakeFiles/module_clientbuffer.dir/znc-data/modules/clientbuffer.cpp.o'.  Stop.
znc_1  | make[1]: *** [CMakeFiles/Makefile2:125: CMakeFiles/module_clientbuffer.dir/all] Error 2
znc_1  | make: *** [Makefile:104: all] Error 2
znc_1  | Traceback (most recent call last):
znc_1  |   File "/opt/znc/bin/znc-buildmod", line 89, in <module>
znc_1  |     subprocess.check_call(['cmake', '--build', '.'], cwd=build)
znc_1  |   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
znc_1  |     raise CalledProcessError(retcode, cmd)
znc_1  | subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 2.
```

**Comment by CyberShadow** [comment]
Please post in full detail all steps you took which led to this problem.

**Comment by gderaco** [comment]
I really can't reproduce i. I will close this and open again if needed. Thanks.
